/** Currency/locale helpers — port of src/common/country.js (compact). */

export const available_currency_priority_map: Record<string, number> = {
  INR: 1,
  USD: 2,
  EUR: 3,
  JPY: 4,
  SGD: 5,
  CNY: 6,
  AUD: 1000,
  GBP: 1000,
  KRW: 1000,
  NZD: 1000,
  RUB: 1000,
  ZAR: 1000,
};

/** Compact map of ISO currency code → symbol (covers all codes in the original country.js). */
const CURRENCY_SYMBOLS: Record<string, string> = {
  AFN: "؋",
  ALL: "L",
  DZD: "د.ج",
  USD: "$",
  AOA: "Kz",
  XCD: "$",
  ARS: "$",
  AMD: "֏",
  AWG: "ƒ",
  AUD: "$",
  AZN: "₼",
  BSD: "$",
  BHD: ".د.ب",
  BDT: "৳",
  BBD: "$",
  BYN: "Br",
  BZD: "$",
  XOF: "Fr",
  BMD: "$",
  BTN: "Nu.",
  BOB: "Bs.",
  BAM: "KM",
  BWP: "P",
  NOK: "kr",
  BRL: "R$",
  BND: "$",
  BGN: "лв",
  BIF: "Fr",
  KHR: "៛",
  XAF: "Fr",
  CAD: "$",
  CVE: "Esc",
  KYD: "$",
  CLP: "$",
  CNY: "¥",
  COP: "$",
  KMF: "Fr",
  CDF: "Fr",
  NZD: "$",
  CRC: "₡",
  HRK: "kn",
  CUC: "$",
  ANG: "ƒ",
  CZK: "Kč",
  DKK: "kr",
  DJF: "Fr",
  DOP: "$",
  EGP: "£",
  ERN: "Nfk",
  ETB: "Br",
  FKP: "£",
  FJD: "$",
  GMD: "D",
  GEL: "ლ",
  GHS: "₵",
  GIP: "£",
  GTQ: "Q",
  GNF: "Fr",
  GYD: "$",
  HTG: "G",
  HNL: "L",
  HKD: "$",
  HUF: "Ft",
  ISK: "kr",
  INR: "₹",
  IDR: "Rp",
  IRR: "﷼",
  IQD: "ع.د",
  EUR: "€",
  ILS: "₪",
  JMD: "$",
  JPY: "¥",
  JOD: "د.ا",
  KZT: "₸",
  KES: "Sh",
  KWD: "د.ك",
  KGS: "с",
  LAK: "₭",
  LBP: "ل.ل",
  LSL: "L",
  LRD: "$",
  LYD: "ل.د",
  CHF: "Fr",
  MOP: "P",
  MKD: "ден",
  MGA: "Ar",
  MWK: "MK",
  MYR: "RM",
  MVR: ".ރ",
  MRU: "UM",
  MUR: "₨",
  MXN: "$",
  MDL: "L",
  MNT: "₮",
  MAD: "د.م.",
  MZN: "MT",
  MMK: "Ks",
  NAD: "$",
  NPR: "₨",
  NIO: "C$",
  NGN: "₦",
  KPW: "₩",
  OMR: "ر.ع.",
  PKR: "₨",
  PAB: "B/.",
  PGK: "K",
  PYG: "₲",
  PEN: "S/.",
  PHP: "₱",
  PLN: "zł",
  QAR: "ر.ق",
  RON: "lei",
  RUB: "₽",
  RWF: "Fr",
  SHP: "£",
  WST: "T",
  STN: "Db",
  SAR: "ر.س",
  RSD: "дин",
  SCR: "₨",
  SLL: "Le",
  SGD: "$",
  SBD: "$",
  SOS: "Sh",
  ZAR: "R",
  KRW: "₩",
  SSP: "£",
  LKR: "₨",
  SDG: "ج.س.",
  SRD: "$",
  SZL: "L",
  SEK: "kr",
  TWD: "$",
  TJS: "ЅМ",
  TZS: "Sh",
  THB: "฿",
  TOP: "T$",
  TTD: "$",
  TND: "د.ت",
  TRY: "₺",
  TMT: "m",
  UGX: "Sh",
  UAH: "₴",
  AED: "د.إ",
  GBP: "£",
  UYU: "$",
  UZS: "so'm",
  VUV: "Vt",
  VES: "Bs.",
  VND: "₫",
  YER: "﷼",
  ZMW: "ZK",
  ZWL: "$",
};

export function GetCurrencySymbol(currency_code: string): string {
  return CURRENCY_SYMBOLS[currency_code] || currency_code;
}

export function GetCurrency(currency_code: string): string {
  return currency_code || "INR";
}

export function GetCurrencyFromObParams(ob_params: any): string {
  return ob_params?.currency || "";
}

// ISO currency code → name, extracted from original country.js currency_locals
const CURRENCY_NAMES: Record<string, string> = {
  "AFN": "Afghan afghani",
  "EUR": "Euro",
  "ALL": "Albanian lek",
  "DZD": "Algerian dinar",
  "USD": "United State Dollar",
  "AOA": "Angolan kwanza",
  "XCD": "East Caribbean dollar",
  "ARS": "Argentine peso",
  "AMD": "Armenian dram",
  "AWG": "Aruban florin",
  "AUD": "Australian dollar",
  "AZN": "Azerbaijani manat",
  "BSD": "Bahamian dollar",
  "BHD": "Bahraini dinar",
  "BDT": "Bangladeshi taka",
  "BBD": "Barbadian dollar",
  "BYN": "New Belarusian ruble",
  "BZD": "Belize dollar",
  "XOF": "West African CFA franc",
  "BMD": "Bermudian dollar",
  "BTN": "Bhutanese ngultrum",
  "BOB": "Bolivian boliviano",
  "BAM": "Bosnia and Herzegovina convertible mark",
  "BWP": "Botswana pula",
  "NOK": "Norwegian krone",
  "BRL": "Brazilian real",
  "BND": "Brunei dollar",
  "BGN": "Bulgarian lev",
  "BIF": "Burundian franc",
  "KHR": "Cambodian riel",
  "XAF": "Central African CFA franc",
  "CAD": "Canadian dollar",
  "CVE": "Cape Verdean escudo",
  "KYD": "Cayman Islands dollar",
  "CLP": "Chilean peso",
  "CNY": "Chinese yuan",
  "COP": "Colombian peso",
  "KMF": "Comorian franc",
  "CDF": "Congolese franc",
  "NZD": "New Zealand dollar",
  "CRC": "Costa Rican colón",
  "HRK": "Croatian kuna",
  "CUC": "Cuban convertible peso",
  "ANG": "Netherlands Antillean guilder",
  "CZK": "Czech koruna",
  "DKK": "Danish krone",
  "DJF": "Djiboutian franc",
  "DOP": "Dominican peso",
  "EGP": "Egyptian pound",
  "ERN": "Eritrean nakfa",
  "ETB": "Ethiopian birr",
  "FKP": "Falkland Islands pound",
  "FJD": "Fijian dollar",
  "XPF": "CFP franc",
  "GMD": "Gambian dalasi",
  "GEL": "Georgian Lari",
  "GHS": "Ghanaian cedi",
  "GIP": "Gibraltar pound",
  "GTQ": "Guatemalan quetzal",
  "GBP": "British pound",
  "GNF": "Guinean franc",
  "GYD": "Guyanese dollar",
  "HTG": "Haitian gourde",
  "HNL": "Honduran lempira",
  "HKD": "Hong Kong dollar",
  "HUF": "Hungarian forint",
  "ISK": "Icelandic króna",
  "INR": "Indian rupee",
  "IDR": "Indonesian rupiah",
  "IRR": "Iranian rial",
  "IQD": "Iraqi dinar",
  "ILS": "Israeli new shekel",
  "JMD": "Jamaican dollar",
  "JPY": "Japanese yen",
  "JOD": "Jordanian dinar",
  "KZT": "Kazakhstani tenge",
  "KES": "Kenyan shilling",
  "KWD": "Kuwaiti dinar",
  "KGS": "Kyrgyzstani som",
  "LAK": "Lao kip",
  "LBP": "Lebanese pound",
  "LSL": "Lesotho loti",
  "LRD": "Liberian dollar",
  "LYD": "Libyan dinar",
  "CHF": "Swiss franc",
  "MOP": "Macanese pataca",
  "MKD": "Macedonian denar",
  "MGA": "Malagasy ariary",
  "MWK": "Malawian kwacha",
  "MYR": "Malaysian ringgit",
  "MVR": "Maldivian rufiyaa",
  "MRO": "Mauritanian ouguiya",
  "MUR": "Mauritian rupee",
  "MXN": "Mexican peso",
  "MDL": "Moldovan leu",
  "MNT": "Mongolian tögrög",
  "MAD": "Moroccan dirham",
  "MZN": "Mozambican metical",
  "MMK": "Burmese kyat",
  "NAD": "Namibian dollar",
  "NPR": "Nepalese rupee",
  "NIO": "Nicaraguan córdoba",
  "NGN": "Nigerian naira",
  "KPW": "North Korean won",
  "OMR": "Omani rial",
  "PKR": "Pakistani rupee",
  "PGK": "Papua New Guinean kina",
  "PYG": "Paraguayan guaraní",
  "PEN": "Peruvian sol",
  "PHP": "Philippine peso",
  "PLN": "Polish złoty",
  "QAR": "Qatari riyal",
  "RON": "Romanian leu",
  "RUB": "Russian ruble",
  "RWF": "Rwandan franc",
  "SHP": "Saint Helena pound",
  "WST": "Samoan tālā",
  "STD": "São Tomé and Príncipe dobra",
  "SAR": "Saudi riyal",
  "RSD": "Serbian dinar",
  "SCR": "Seychellois rupee",
  "SLL": "Sierra Leonean leone",
  "SGD": "Singapore dollar",
  "SBD": "Solomon Islands dollar",
  "SOS": "Somali shilling",
  "ZAR": "South African rand",
  "KRW": "South Korean won",
  "SSP": "South Sudanese pound",
  "LKR": "Sri Lankan rupee",
  "SDG": "Sudanese pound",
  "SRD": "Surinamese dollar",
  "SZL": "Swazi lilangeni",
  "SEK": "Swedish krona",
  "SYP": "Syrian pound",
  "TWD": "New Taiwan dollar",
  "TJS": "Tajikistani somoni",
  "TZS": "Tanzanian shilling",
  "THB": "Thai baht",
  "TOP": "Tongan paʻanga",
  "TTD": "Trinidad and Tobago dollar",
  "TND": "Tunisian dinar",
  "TRY": "Turkish lira",
  "TMT": "Turkmenistan manat",
  "UGX": "Ugandan shilling",
  "UAH": "Ukrainian hryvnia",
  "AED": "United Arab Emirates dirham",
  "UYU": "Uruguayan peso",
  "UZS": "Uzbekistani so'm",
  "VUV": "Vanuatu vatu",
  "VEF": "Venezuelan bolívar",
  "VND": "Vietnamese đồng",
  "YER": "Yemeni rial",
  "ZMW": "Zambian kwacha",
};

export const currency_list = Object.entries(CURRENCY_SYMBOLS).map(([currency_code, currency_symbol]) => ({
  currency_code,
  currency_symbol,
  currency_name: CURRENCY_NAMES[currency_code] || currency_code,
  country_name: currency_code,
}));
