/** Currency/locale helpers — port of src/common/country.js (compact). */

export const available_currency_priority_map: Record<string, number> = {
  INR: 1,
  USD: 2,
  EUR: 3,
  JPY: 4,
  SGD: 5,
  CNY: 6,
  AUD: 1000,
  GBP: 1000,
  KRW: 1000,
  NZD: 1000,
  RUB: 1000,
  ZAR: 1000,
};

/** Compact map of ISO currency code → symbol (covers all codes in the original country.js). */
const CURRENCY_SYMBOLS: Record<string, string> = {
  AFN: "؋",
  ALL: "L",
  DZD: "د.ج",
  USD: "$",
  AOA: "Kz",
  XCD: "$",
  ARS: "$",
  AMD: "֏",
  AWG: "ƒ",
  AUD: "$",
  AZN: "₼",
  BSD: "$",
  BHD: ".د.ب",
  BDT: "৳",
  BBD: "$",
  BYN: "Br",
  BZD: "$",
  XOF: "Fr",
  BMD: "$",
  BTN: "Nu.",
  BOB: "Bs.",
  BAM: "KM",
  BWP: "P",
  NOK: "kr",
  BRL: "R$",
  BND: "$",
  BGN: "лв",
  BIF: "Fr",
  KHR: "៛",
  XAF: "Fr",
  CAD: "$",
  CVE: "Esc",
  KYD: "$",
  CLP: "$",
  CNY: "¥",
  COP: "$",
  KMF: "Fr",
  CDF: "Fr",
  NZD: "$",
  CRC: "₡",
  HRK: "kn",
  CUC: "$",
  ANG: "ƒ",
  CZK: "Kč",
  DKK: "kr",
  DJF: "Fr",
  DOP: "$",
  EGP: "£",
  ERN: "Nfk",
  ETB: "Br",
  FKP: "£",
  FJD: "$",
  GMD: "D",
  GEL: "ლ",
  GHS: "₵",
  GIP: "£",
  GTQ: "Q",
  GNF: "Fr",
  GYD: "$",
  HTG: "G",
  HNL: "L",
  HKD: "$",
  HUF: "Ft",
  ISK: "kr",
  INR: "₹",
  IDR: "Rp",
  IRR: "﷼",
  IQD: "ع.د",
  EUR: "€",
  ILS: "₪",
  JMD: "$",
  JPY: "¥",
  JOD: "د.ا",
  KZT: "₸",
  KES: "Sh",
  KWD: "د.ك",
  KGS: "с",
  LAK: "₭",
  LBP: "ل.ل",
  LSL: "L",
  LRD: "$",
  LYD: "ل.د",
  CHF: "Fr",
  MOP: "P",
  MKD: "ден",
  MGA: "Ar",
  MWK: "MK",
  MYR: "RM",
  MVR: ".ރ",
  MRU: "UM",
  MUR: "₨",
  MXN: "$",
  MDL: "L",
  MNT: "₮",
  MAD: "د.م.",
  MZN: "MT",
  MMK: "Ks",
  NAD: "$",
  NPR: "₨",
  NIO: "C$",
  NGN: "₦",
  KPW: "₩",
  OMR: "ر.ع.",
  PKR: "₨",
  PAB: "B/.",
  PGK: "K",
  PYG: "₲",
  PEN: "S/.",
  PHP: "₱",
  PLN: "zł",
  QAR: "ر.ق",
  RON: "lei",
  RUB: "₽",
  RWF: "Fr",
  SHP: "£",
  WST: "T",
  STN: "Db",
  SAR: "ر.س",
  RSD: "дин",
  SCR: "₨",
  SLL: "Le",
  SGD: "$",
  SBD: "$",
  SOS: "Sh",
  ZAR: "R",
  KRW: "₩",
  SSP: "£",
  LKR: "₨",
  SDG: "ج.س.",
  SRD: "$",
  SZL: "L",
  SEK: "kr",
  TWD: "$",
  TJS: "ЅМ",
  TZS: "Sh",
  THB: "฿",
  TOP: "T$",
  TTD: "$",
  TND: "د.ت",
  TRY: "₺",
  TMT: "m",
  UGX: "Sh",
  UAH: "₴",
  AED: "د.إ",
  GBP: "£",
  UYU: "$",
  UZS: "so'm",
  VUV: "Vt",
  VES: "Bs.",
  VND: "₫",
  YER: "﷼",
  ZMW: "ZK",
  ZWL: "$",
};

export function GetCurrencySymbol(currency_code: string): string {
  return CURRENCY_SYMBOLS[currency_code] || currency_code;
}

export function GetCurrency(currency_code: string): string {
  return currency_code || "INR";
}

export function GetCurrencyFromObParams(ob_params: any): string {
  return ob_params?.currency || "";
}

export const currency_list = Object.entries(CURRENCY_SYMBOLS).map(([currency_code, currency_symbol]) => ({
  currency_code,
  currency_symbol,
  currency_name: currency_code,
  country_name: currency_code,
}));
